signo(hola, saludos, 'SAL001').
signo(buenos_dias, saludos, 'SAL002').
signo(buenas_tardes, saludos, 'SAL003').
signo(buenas_noches, saludos, 'SAL004').
signo(gracias, saludos, 'SAL005').
signo(por_favor, saludos, 'SAL006').
signo(adios, saludos, 'SAL007').
signo(como_estas, saludos, 'SAL008').
signo(buen_dia, saludos, 'SAL009').
signo(que_onda, saludos, 'SAL010').
